spring:
  datasource:
    url: jdbc:mysql://192.168.33.120:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Mysql@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
server:
  port: 8082

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl